### ISSUE TITLE
Monitor with time machine argument clears all releases instead of just new artists

### ISSUE THREAD

**Issue by Critical-Impact** [digitalec/deemon#51] opened 2022-01-13 02:01 UTC
Hi, I am running 
`deemon monitor --import /downloads/artists.txt -T 2021-01-01 `
to get new artists up to speed before using refresh on a cron. 
Deemon appears to wipe out all the releases after this date for all artists, instead of just the newly added ones. I'm not sure if this was the intention as in the usage examples it has 
`-T, --time-machine YYYY-MM-DD  Refresh newly added artists on this date`

All my artists are in this file and I append new ones to the end

**Comment by digitalec** [comment] 2022-01-19 01:11
I just tried reproducing this issue on 2.8.2 and 2.9.0-beta2 and was not able to reproduce it. Please try again and let me know.

**Comment by digitalec** [comment] 2022-01-19 01:38
Issue is resolved and will be in next beta of 2.9 (beta 3)

**Closed by digitalec** 2022-01-19 01:38 UTC
Labels: bug

**Comment by digitalec** [comment] 2022-02-03 00:33
This is now also patched in the latest stable release, 2.8.3.
